### ISSUE TITLE
Support sub-thread starting points

### ISSUE THREAD

**Issue by mwarkentin** [rneatherway/gh-slack#46]
Not sure if I've never tried this before, or if Slack just changed something, but recently I copied a link to a message within a thread (I didn't care about anything before it in the thread) and using this link on `gh-slack` didn't work:

```
❯ gh slack --limit=1000 https://*****.slack.com/archives/C0220QQNUHE/p1684440714803369?thread_ts=1684440607.895759&cid=C0220QQNUHE | pbcopy
[1] 24189
zsh: no matches found: https://*****.slack.com/archives/C0220QQNUHE/p1684440714803369?thread_ts=1684440607.895759
[1]  + exit 1     gh slack --limit=1000
```

When I grabbed the first message in the thread the URL didn't have the query params and worked:

```
❯ gh slack --limit=1000 https://*****.slack.com/archives/C0220QQNUHE/p1684440714803369 | pbcopy
```

Ideally this would grab the contents of the thread starting from that point, but I'd also be ok if it just ignored the query params and pulled the whole thread.

**Comment by mwarkentin** [comment]
I'll try that and let you know, thanks!

**Comment by rneatherway** [comment]
Hi @mwarkentin, I think the issue is down to the parsing of the permalink. Here is an example link for the first message in a thread:

    https://sanity-io-land.slack.com/archives/C9Y51FDGA/p1709663536325529

No query parameters!

One for the third message in a thread:

    https://sanity-io-land.slack.com/archives/C9Y51FDGA/p1709664320730949?thread_ts=1709663536.325529&cid=C9Y51FDGA

This code doesn't look at the query parameters at all: https://github.com/rneatherway/gh-slack/blob/86f738fbb4ce220d71eff7e08151aef4d96e2d69/cmd/gh-slack/cmd/read.go#L42-L55

That means that it's the same as just requesting all the top level messages in the channel after the time of the original message in the thread.

I think just using the `thread_ts` query parameter if it exists would fix the issue. You can validate that by trying:

    gh slack api get conversations.replies -f channel= C06MA1ST3B5 -f ts=1709320542.716369

and seeing if the expected messages come out.

**Comment by rneatherway** [comment]
@mwarkentin I've put together a fix, which was a little more complicated than I thought, over at #60. Could you give it a try please? If you check out that PR then you can run:

    go run ./cmd/gh-slack/ --limit=1000 'https://sentry.slack.com/archives/C06MA1ST3B5/p1709648390444389?thread_ts=1709320542.716369&cid=C06MA1ST3B5'

**Comment by mwarkentin** [comment]
Confirmed fixed over here: https://github.com/rneatherway/gh-slack/pull/60#issuecomment-2000216951
