### ISSUE TITLE
Move markdown to `slack` module

### ISSUE THREAD

**Issue by nobe4** [rneatherway/gh-slack#64]
I think that https://github.com/rneatherway/gh-slack/tree/main/internal/markdown would be better suited to live in https://github.com/rneatherway/slack and maybe having a `markdown => slack-markdown` function as well.

This would allow other clients to format markdown based on the code you've already written :)

What do you think? 

If that's acceptable I'll PR that :)

**Comment by rneatherway** [comment]
> I think that https://github.com/rneatherway/gh-slack/tree/main/internal/markdown would be better suited to live in https://github.com/rneatherway/slack and maybe having a `markdown => slack-markdown` function as well.
> 
> This would allow other clients to format markdown based on the code you've already written :)
> 
> What do you think?

Sure, that seems to make sense. I thought it might be a bit awkward because of the username cache but it looks like there is already an interface covering that part.

I'm not quite sure what you mean by `markdown => slack-markdown` but if you think it's useful then it probably is and the PR will explain it to me :wink:

**Comment by nobe4** [comment]
> I'm not quite sure what you mean by `markdown => slack-markdown`

Currently your code does `slack-markdown => markdown`, so I am thinking that a function that does the reverse would be useful as well.

I only wished slack didn't have its own version of markdown, feels unnecessarily convoluted.

**Comment by nobe4** [comment]
Here you go:

- https://github.com/rneatherway/gh-slack/pull/65
- https://github.com/rneatherway/slack/pull/4

This does only the `slack-markdown => markdown` for now, since it might not be accepted. But if it is, I might spend some extra time to do the reverse :)

**Comment by rneatherway** [comment]
Both PRs LGTM, feel free to merge when ready.

As an FYI, a couple of thoughts that I had that are relevant here:

1. I imagined that at some point it would make sense to move to the "rich" version of the Slack messages. By which I mean if you look at https://api.slack.com/surfaces/messages#payloads we are currently using `text` and it might be easier to give a consistently good result by instead reading `blocks`.
2. I would like to keep the `slack` package at 0.x for a while and reserve the right to make breaking changes to it as I'm far from confident that the split is in the right place or that certain APIs are the best they can be. I expect that only this repo and possibly whatever you are using it for are the only consumers so far though so that isn't likely to be an issue!

**Comment by nobe4** [comment]
> Both PRs LGTM, feel free to merge when ready.

🙏 🎉 

1. Agreed, the `text` is very limited and whenever I try to send 'fancy' messages, I always use attachments/blocks. However, this might already be possible via `slackclient.API` ?
2. Definitely, I am working on another client atm (will share more when it's doing something good) and happy to adapt my code if the `slack` package changes :)

**Comment by rneatherway** [comment]
> * Agreed, the `text` is very limited and whenever I try to send 'fancy' messages, I always use attachments/blocks. However, this might already be possible via `slackclient.API` ?

I was thinking more of reading rather than writing. That is, when downloading Slack messages to convert them to github-flavoured markdown use the blocks as input rather than `text`.

**Comment by rneatherway** [comment]
> This does only the `slack-markdown => markdown` for now, since it might not be accepted. But if it is, I might spend some extra time to do the reverse :)

Perfectly happy to accept the inverse function as well if you'd like to add that.

**Comment by nobe4** [comment]
For now I'll not do that, so I'll close the ticket :)
